backend:
    name: git-gateway
    branch: main

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://codestitch.app/frontend/images/logo.png

media_folder: "src/assets/images/blog"
public_folder: "/assets/images/blog"

collections:
    - name: "blog"
      label: "Blog"
      folder: "src/content/blog"
      create: true
      slug: "{{slug}}"
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
                label: "URL Slug",
                name: "url",
                widget: "string",
                hint: 'Specify where the page will be written to. If you use "Blog Post", the post will be accessible from "blog/blog-post"',
            }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Author", name: "author", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
          - { label: "Featured Image", name: "image", widget: "image" }
          - { label: "Image Caption", name: "imageAlt", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Image Gallery"             # Label shown in the CMS UI
            name: "gallery"                  # Name used in your template files (e.g., post.gallery)
            widget: "list"                   # Use the list widget for multiple items
            summary: "{{fields.image}}"      # Optional: Show image path in collapsed view
            field:                           # Define the single field to repeat
              label: "Image"                 # Label for the individual image upload
              name: "image"                  # Name for the image field within each list item
              widget: "image"                # Use the image widget for uploading
              media_library:                 # Optional: Fine-tune media library options
                allow_multiple: false        # Set to true if you want multi-select *per add*
        # --- Optional List Widget Settings ---
        # allow_add: true                # Default is true, set to false to prevent adding more
        # collapsed: true                # Default is true, set to false to show items expanded
        # label_singular: "Image"        # Customize the 'Add Item' button text
